# Generated by Django 3.2.2 on 2021-05-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_fluent_app', '0007_remove_result_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
